{"name": "test_failed", "status": "failed", "statusDetails": {"message": "AssertionError: Some fail reason\nassert False", "trace": "def test_failed():\n>       assert False, \"Some fail reason\"\nE       AssertionError: Some fail reason\nE       assert False\n\ntest\\allure_status_test.py:9: AssertionError"}, "start": 1754039810212, "stop": 1754039810212, "uuid": "5ab69f08-443a-4196-a95f-ca3c92c846aa", "historyId": "8a8772d2a94ba22adc036c24014cb205", "testCaseId": "8a8772d2a94ba22adc036c24014cb205", "fullName": "test.allure_status_test#test_failed", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "allure_status_test"}, {"name": "host", "value": "MININT-EL9T967"}, {"name": "thread", "value": "26968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.allure_status_test"}], "titlePath": ["test", "allure_status_test.py"]}