{"name": "test_xfail", "status": "skipped", "statusDetails": {"message": "XFAIL Some xfail reason\n\nAssertionError: Assertion failed\nassert False", "trace": "@pytest.mark.xfail(reason=\"Some xfail reason\")\n    def test_xfail():\n>       assert False, \"Assertion failed\"\nE       AssertionError: Assertion failed\nE       assert False\n\ntest\\allure_status_test.py:24: AssertionError"}, "start": 1754039810368, "stop": 1754039810368, "uuid": "5e9f2e3e-6f50-405a-86da-259b91a9e1c9", "historyId": "77aa3ee7069d023b0fd97f7c40d7d179", "testCaseId": "77aa3ee7069d023b0fd97f7c40d7d179", "fullName": "test.allure_status_test#test_xfail", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "allure_status_test"}, {"name": "host", "value": "MININT-EL9T967"}, {"name": "thread", "value": "26968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.allure_status_test"}], "titlePath": ["test", "allure_status_test.py"]}